//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("3.2.0.34")]
[assembly: AssemblyVersion("3.2.0.34")]
[assembly: AssemblyInformationalVersion("3.2.0-UseGitVersion1.34+Branch.UseGitVersion1.Sha.3b4677d87df75d2b3ac53332b9731a3792b5e618")]
