// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Text;

namespace Iot.Device.Graphics
{
    /// <summary>
    /// Provides the character encoding for an LCD display.
    /// Instances of this class are generated by <see cref="LcdCharacterEncodingFactory"/>.
    /// </summary>
    public class LcdCharacterEncoding : Encoding
    {
        private readonly Dictionary<char, byte> _characterMapping;
        private readonly char _unknownLetter;
        // Character pixel maps for characters that will need to be written to the character RAM for this code page
        private readonly List<byte[]> _extraCharacters;
        private readonly string _cultureName;

        /// <summary>
        /// Creates an instance of <see cref="LcdCharacterEncoding"/>.
        /// </summary>
        /// <param name="cultureName">Culture name for this encoding (informational only)</param>
        /// <param name="readOnlyMemoryName">Name of the ROM (hard coded read-only character memory) on the display</param>
        /// <param name="characterMap">The character map to use</param>
        /// <param name="unknownLetter">The character to print when a letter not in the map is found. This letter must be part of the map</param>
        public LcdCharacterEncoding(string cultureName, string readOnlyMemoryName, Dictionary<char, byte> characterMap, char unknownLetter)
        {
            _cultureName = cultureName;
            _characterMapping = characterMap;
            _unknownLetter = unknownLetter;
            _extraCharacters = new List<byte[]>();
            AllCharactersSupported = true;
            ReadOnlyMemoryName = readOnlyMemoryName;
            if (!_characterMapping.ContainsKey(unknownLetter))
            {
                throw new ArgumentException($"The replacement letter {unknownLetter} is not part of the character map", nameof(unknownLetter));
            }
        }

        /// <summary>
        /// Creates an instance of <see cref="LcdCharacterEncoding"/>.
        /// </summary>
        /// <param name="cultureName">Culture name for this encoding (informational only)</param>
        /// <param name="readOnlyMemoryName">Name of the ROM (hard coded read-only character memory) on the display</param>
        /// <param name="characterMap">The character map to use</param>
        /// <param name="unknownLetter">The character to print when a letter not in the map is found</param>
        /// <param name="extraCharacters">The pixel map of characters required for this culture but not found in the character ROM</param>
        public LcdCharacterEncoding(string cultureName, string readOnlyMemoryName, Dictionary<char, byte> characterMap, char unknownLetter, List<byte[]> extraCharacters)
            : this(cultureName, readOnlyMemoryName, characterMap, unknownLetter)
        {
            _extraCharacters = extraCharacters;
            AllCharactersSupported = true;
        }

        /// <summary>
        /// Always returns true for this class.
        /// </summary>
        public override bool IsSingleByte => true;

        /// <inheritDoc/>
        public override string EncodingName => _cultureName;

        /// <summary>
        /// The list of pixel maps for extra characters that are required for this culture.
        /// </summary>
        public virtual List<byte[]> ExtraCharacters => _extraCharacters;

        /// <summary>
        /// This is internally set to false if we already know that we won't be able to display all required characters
        /// </summary>
        public bool AllCharactersSupported { get; set; }

        /// <summary>
        /// Specified Name of the hardcoded character memory set for which this Encoding is intended. An encoding shall only be loaded to
        /// a matching display.
        /// </summary>
        public string ReadOnlyMemoryName { get; }

        /// <summary>
        /// Returns the number of bytes that are required to encode the given characters
        /// </summary>
        /// <returns>This implementation always returns count.</returns>
        public override int GetByteCount(char[] chars, int index, int count)
        {
            if (index + count > chars.Length || index < 0 || count < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(index), "Index + count must be smaller than array length");
            }

            return count;
        }

        /// <summary>
        /// Encodes the given characters
        /// </summary>
        /// <param name="chars">Characters to encode</param>
        /// <param name="charIndex">First character to encode</param>
        /// <param name="charCount">Number of characters to encode</param>
        /// <param name="bytes">Output byte array</param>
        /// <param name="byteIndex">Offset at which to start writing</param>
        /// <returns>The number of bytes written</returns>
        public override int GetBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex)
        {
            for (int i = 0; i < charCount; i++)
            {
                byte b;
                if (_characterMapping is null)
                {
                    bytes[byteIndex] = (byte)chars[charIndex];
                }
                else if (_characterMapping.TryGetValue(chars[charIndex], out b))
                {
                    bytes[byteIndex] = b;
                }
                else
                {
                    bytes[byteIndex] = _characterMapping[_unknownLetter];
                }

                byteIndex++;
                charIndex++;
            }

            return charCount;
        }

        /// <summary>
        /// Returns the number of characters that will be generated from the input set.
        /// </summary>
        /// <param name="bytes">Input bytes</param>
        /// <param name="index">Start index</param>
        /// <param name="count">Number of bytes to decode</param>
        /// <returns>The number of characters that would be generated</returns>
        public override int GetCharCount(byte[] bytes, int index, int count) => Math.Min(bytes.Length, count);

        /// <summary>
        /// Reverse mapping is not supported for this encoding.
        /// </summary>
        /// <returns>Never returns</returns>
        public override int GetChars(byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) => throw new NotSupportedException("Reverse conversion not supported");

        /// <summary>
        /// Returns the maximum number of bytes for the given character count.
        /// </summary>
        /// <param name="charCount">Input character count</param>
        /// <returns>The input value. This encoding always uses an 1:1 mapping</returns>
        public override int GetMaxByteCount(int charCount) => charCount;

        /// <summary>
        /// Returns the maximum number of characters for the given byte count.
        /// </summary>
        /// <param name="byteCount">Input byte count</param>
        /// <returns>The input value. This encoding always uses an 1:1 mapping</returns>
        public override int GetMaxCharCount(int byteCount) => byteCount;
    }
}
