//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 
namespace Iot.Device.Nmea0183 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DeviationTable.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DeviationTable.xsd", IsNullable=false)]
    public partial class Identification {
        
        private string shipNameField;
        
        private string callsignField;
        
        private string mMSIField;
        
        private System.DateTime calibrationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShipName {
            get {
                return this.shipNameField;
            }
            set {
                this.shipNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Callsign {
            get {
                return this.callsignField;
            }
            set {
                this.callsignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MMSI {
            get {
                return this.mMSIField;
            }
            set {
                this.mMSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime CalibrationDate {
            get {
                return this.calibrationDateField;
            }
            set {
                this.calibrationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DeviationTable.xsd")]
    public partial class DeviationPoint {
        
        private float compassReadingField;
        
        private float magneticHeadingField;
        
        private float deviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float CompassReading {
            get {
                return this.compassReadingField;
            }
            set {
                this.compassReadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float MagneticHeading {
            get {
                return this.magneticHeadingField;
            }
            set {
                this.magneticHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Deviation {
            get {
                return this.deviationField;
            }
            set {
                this.deviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DeviationTable.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DeviationTable.xsd", IsNullable=false)]
    public partial class CompassCalibrationData {
        
        private DeviationPoint[] pointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Points", Order=0)]
        public DeviationPoint[] Points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
    }
}
