<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultBindingTfms)</TargetFrameworks>
    <!--Disabling default items so samples source won't get build by the main library-->
    <EnableDefaultItems>false</EnableDefaultItems>
    <RootNamespace>Iot.Device.Nmea0183</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="Sentences/*.cs" />
    <Compile Include="Ais/*.cs" />
    <Compile Include="AisSentences/*.cs" />
    <None Include="DeviationTable.xsd" />
    <None Include="README.md" />
    <None Include="Seatalk1\README-Seatalk.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rtc\Rtc.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsLoggingPackageVersion)" />
  </ItemGroup>
  <!-- Make the internal classes visible to the unit test assembly -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Seatalk1\AutoPilotRemoteController.cs" />
    <Compile Include="Seatalk1\Seatalk1Parser.cs" />
    <Compile Include="Seatalk1\SeatalkInterface.cs" />
    <Compile Include="Seatalk1\SeatalkToNmeaConverter.cs" />
    <Compile Include="Sentences\Seatalk1\ApparentWindAngle.cs" />
    <Compile Include="Sentences\Seatalk1\ApparentWindSpeed.cs" />
    <Compile Include="Sentences\Seatalk1\AutopilotAlarms.cs" />
    <Compile Include="Sentences\Seatalk1\AutopilotButtons.cs" />
    <Compile Include="Sentences\Seatalk1\AutopilotCalibrationParameter.cs" />
    <Compile Include="Sentences\Seatalk1\AutopilotCalibrationParameterMessage.cs" />
    <Compile Include="Sentences\Seatalk1\AutopilotWindStatus.cs" />
    <Compile Include="Sentences\Seatalk1\CompassHeadingAndRudderPosition.cs" />
    <Compile Include="Sentences\Seatalk1\CompassHeadingAutopilotCourse.cs" />
    <Compile Include="Sentences\Seatalk1\CompassHeadingAutopilotCourseAlt.cs" />
    <Compile Include="Sentences\Seatalk1\CourseComputerStatus.cs" />
    <Compile Include="Sentences\Seatalk1\CourseComputerWarnings.cs" />
    <Compile Include="Sentences\Seatalk1\DeadbandMode.cs" />
    <Compile Include="Sentences\Seatalk1\DeadbandSetting.cs" />
    <Compile Include="Sentences\Seatalk1\DeviceIdentification.cs" />
    <Compile Include="Sentences\Seatalk1\DisplayBacklightLevel.cs" />
    <Compile Include="Sentences\Seatalk1\Keystroke.cs" />
    <Compile Include="Sentences\Seatalk1\NavigationToWaypoint.cs" />
    <Compile Include="Sentences\Seatalk1\SeatalkMessage.cs" />
    <Compile Include="Sentences\Seatalk1\SetLampIntensity.cs" />
    <Compile Include="Sentences\Seatalk1\SpeedTroughWater.cs" />
    <Compile Include="Sentences\Seatalk1\TargetWaypointName.cs" />
    <Compile Include="Sentences\Seatalk1\TurnDirection.cs" />
  </ItemGroup>
</Project>
